# Generated by Django 2.1.7 on 2019-03-09 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=4096)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=4096)),
                ('email_password', models.CharField(max_length=4096)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('victim_id', models.BigIntegerField()),
                ('victim_username', models.CharField(max_length=1028)),
                ('status', models.PositiveIntegerField(choices=[(0, 'unfollow'), (1, 'follow'), (2, 'processed'), (3, 'not_found'), (4, 'requested'), (5, 'unrequested'), (6, 'block'), (7, 'unblock')])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Accounts')),
            ],
            options={
                'db_table': 'following',
            },
        ),
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('victim_id', models.BigIntegerField()),
                ('victim_username', models.CharField(max_length=1028)),
                ('picture_id', models.CharField(max_length=1024, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Accounts')),
            ],
            options={
                'db_table': 'liked',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipk', models.BigIntegerField(db_index=True)),
                ('username', models.CharField(blank=True, max_length=1024)),
                ('full_name', models.CharField(blank=True, default='', max_length=1024)),
                ('is_private', models.BooleanField(default=False)),
                ('profile_pic_url', models.URLField(blank=True, default='', max_length=4096)),
                ('profile_pic_id', models.CharField(default='', max_length=1024)),
                ('is_verified', models.BooleanField(default=False)),
                ('has_anonymous_profile_picture', models.BooleanField(default=False)),
                ('media_count', models.PositiveIntegerField()),
                ('follower_count', models.PositiveIntegerField()),
                ('following_count', models.PositiveIntegerField()),
                ('following_tag_count', models.PositiveIntegerField()),
                ('biography', models.TextField(blank=True, default='')),
                ('external_url', models.URLField(blank=True, default='', max_length=4096)),
                ('total_igtv_videos', models.PositiveIntegerField()),
                ('total_ar_effects', models.PositiveIntegerField()),
                ('reel_auto_archive', models.CharField(blank=True, max_length=1024)),
                ('usertags_count', models.PositiveIntegerField()),
                ('is_favorite', models.BooleanField()),
                ('is_interest_account', models.BooleanField()),
                ('hd_profile_pic_url_info', models.URLField(blank=True, default='', max_length=4096)),
                ('mutual_followers_count', models.PositiveIntegerField()),
                ('has_highlight_reels', models.BooleanField()),
                ('can_be_reported_as_fraud', models.BooleanField()),
                ('direct_messaging', models.CharField(blank=True, max_length=1024)),
                ('fb_page_call_to_action_id', models.CharField(blank=True, max_length=1024)),
                ('address_street', models.CharField(blank=True, max_length=1024)),
                ('business_contact_method', models.CharField(blank=True, max_length=1024)),
                ('category', models.CharField(blank=True, max_length=1024)),
                ('city_id', models.BigIntegerField(blank=True, null=True)),
                ('city_name', models.CharField(blank=True, max_length=1024)),
                ('contact_phone_number', models.CharField(blank=True, max_length=1024)),
                ('is_call_to_action_enabled', models.BooleanField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('public_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('public_phone_country_code', models.CharField(blank=True, max_length=1024)),
                ('public_phone_number', models.CharField(blank=True, max_length=1024)),
                ('zip', models.CharField(blank=True, max_length=1024)),
                ('instagram_location_id', models.CharField(blank=True, max_length=1024)),
                ('is_business', models.BooleanField()),
                ('account_type', models.BigIntegerField()),
                ('can_hide_public_contacts', models.BooleanField()),
                ('should_show_category', models.BooleanField()),
                ('should_show_public_contacts', models.BooleanField()),
                ('include_direct_blacklist_status', models.BooleanField()),
                ('is_potential_business', models.BooleanField()),
                ('is_bestie', models.BooleanField()),
                ('has_unseen_besties_media', models.BooleanField()),
                ('show_account_transparency_details', models.BooleanField()),
                ('auto_expand_chaining', models.BooleanField()),
                ('highlight_reshare_disabled', models.BooleanField()),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
