# Generated by Django 2.1.7 on 2019-03-09 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20190309_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ipk',
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
    ]
