# Generated by Django 2.1.7 on 2019-03-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20190309_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('parser_name', models.CharField(max_length=1024)),
                ('text', models.TextField()),
                ('post_id', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'parsed_text',
            },
        ),
    ]
