# Generated by Django 2.1.7 on 2019-03-10 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_parsedtext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('instagram_id', models.CharField(max_length=1024)),
                ('url', models.URLField(max_length=1024)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Accounts')),
                ('text', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.ParsedText')),
            ],
            options={
                'db_table': 'posted',
            },
        ),
    ]
