# Generated by Django 2.1.7 on 2019-03-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_posted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('chat', models.CharField(max_length=1024)),
                ('is_enable', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'approved_chat',
            },
        ),
    ]
