# Generated by Django 2.1.7 on 2019-03-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20190311_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvedchat',
            name='is_enable',
        ),
        migrations.AlterField(
            model_name='approvedchat',
            name='chat',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
