# Generated by Django 2.1.7 on 2019-03-12 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_auto_20190312_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('parser_name', models.CharField(max_length=1024)),
                ('text', models.TextField()),
                ('post_id', models.CharField(max_length=1024)),
                ('image_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('instagram_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Posted')),
            ],
            options={
                'db_table': 'text_content',
            },
        ),
    ]
