# Generated by Django 2.1.7 on 2019-03-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_textcontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textcontent',
            old_name='image_name',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='approved',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
