# Generated by Django 2.1.7 on 2019-03-12 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_auto_20190312_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='textcontent',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Accounts'),
        ),
    ]
