# Generated by Django 2.1.7 on 2019-03-13 07:54

from django.db import migrations

update_sql = '''UPDATE text_content SET approved = NULL'''


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_textcontent_owner'),
    ]

    operations = [
        migrations.RunSQL(update_sql)
    ]
