# Generated by Django 2.1.7 on 2019-03-16 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_ignored'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic_hd',
            new_name='profile_pic_url_hd',
        ),
    ]
