# Generated by Django 2.1.7 on 2019-03-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_auto_20190316_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='source_username',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
