# Generated by Django 2.1.7 on 2019-03-17 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_profile_source_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='source_username',
        ),
        migrations.AddField(
            model_name='profile',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Accounts'),
        ),
    ]
