# Generated by Django 2.1.7 on 2019-03-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0026_auto_20190317_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='came_from_id',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='came_from_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
