# Generated by Django 2.1.7 on 2019-03-17 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0027_auto_20190317_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='came_from_id',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='profile',
            name='came_from_name',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='profile',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Accounts'),
        ),
    ]
