# Generated by Django 2.1.7 on 2019-03-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0028_auto_20190317_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='following',
            name='has_request',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liked',
            name='has_request',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
