# Generated by Django 2.1.7 on 2019-03-18 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0030_auto_20190318_0925'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ignored',
            unique_together={('profile', 'owner')},
        ),
    ]
