# Generated by Django 2.1.7 on 2019-03-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0031_auto_20190318_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='promo_type',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2)], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='following',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='following',
            name='has_request',
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='following',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'unfollow'), (1, 'follow'), (2, 'processed'), (3, 'not_found'), (4, 'requested'), (5, 'unrequested'), (6, 'block'), (7, 'unblock')], db_index=True),
        ),
        migrations.AlterField(
            model_name='ignored',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='liked',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='liked',
            name='has_request',
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='media_count',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
