# Generated by Django 2.1.7 on 2019-03-21 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0033_ignored_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(max_length=1024)),
                ('request_time', models.DateTimeField()),
                ('request_headers', models.TextField()),
                ('request_body', models.TextField(null=True)),
                ('response_time', models.DateTimeField(null=True)),
                ('status_code', models.PositiveIntegerField(null=True)),
                ('response_headers', models.TextField(null=True)),
                ('response_body', models.TextField(null=True)),
                ('error', models.TextField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Accounts')),
            ],
            options={
                'db_table': 'ig_log',
            },
        ),
    ]
