# Generated by Django 2.1.7 on 2019-03-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0036_iglog_request_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iglog',
            name='request_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='iglog',
            name='status_code',
            field=models.PositiveIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='iglog',
            name='url',
            field=models.URLField(db_index=True, max_length=1024),
        ),
    ]
