# Generated by Django 2.1.7 on 2019-03-22 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0037_auto_20190321_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='created',
            new_name='opened',
        ),
    ]
