# Generated by Django 2.1.7 on 2019-03-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0038_auto_20190322_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='following',
            name='closed',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
