# Generated by Django 2.1.7 on 2019-03-22 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0039_following_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='has_request',
        ),
        migrations.RemoveField(
            model_name='liked',
            name='has_request',
        ),
    ]
