# Generated by Django 2.1.7 on 2019-03-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0040_auto_20190322_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
