# Generated by Django 2.1.7 on 2019-03-24 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0042_auto_20190322_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('followers_count', models.BigIntegerField()),
                ('following_count', models.BigIntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Accounts')),
            ],
            options={
                'db_table': 'ig_stat',
            },
        ),
    ]
