# Generated by Django 2.1.7 on 2019-04-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0045_auto_20190403_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounts',
            name='phone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='proxy_id',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
