# Generated by Django 2.1.7 on 2019-04-08 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0046_auto_20190408_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='proxy_id',
            new_name='proxy_ip',
        ),
    ]
