# Generated by Django 2.1.7 on 2019-04-10 19:45
import itertools

from django.db import migrations

proxy_user = 'proxy_user'
proxy_password = 'proxy_password'
proxy_port = 4128

proxy_ips = [
    '185.188.183.28',
    '185.188.183.222',
    '185.189.12.112',
    '185.189.12.209',
    '185.189.13.50',
    '185.189.14.36',
    '185.189.15.12',
    '185.195.24.172',
    '185.195.25.98',
    '185.195.26.199',
]


def add_proxies(apps, schema_editor):
    Proxy = apps.get_model('database', 'Proxy')
    for proxy in proxy_ips:
        Proxy.objects.create(
            ip=proxy,
            port=proxy_port,
            username=proxy_user,
            password=proxy_password
        )


def set_proxies(apps, schema_editor):
    Accounts = apps.get_model('database', 'Accounts')
    Proxy = apps.get_model('database', 'Proxy')
    proxies_cycle = itertools.cycle(Proxy.objects.all())
    for account in Accounts.objects.filter(banned=False):
        account.proxy = next(proxies_cycle)
        account.save()


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0048_auto_20190410_1944'),
    ]

    operations = [
        migrations.RunPython(add_proxies),
        migrations.RunPython(set_proxies),
    ]
