# Generated by Django 2.1.7 on 2019-04-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0049_auto_20190410_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=1024)),
                ('instagram_id', models.BigIntegerField(db_index=True, unique=True)),
            ],
            options={
                'db_table': 'source_profile',
            },
        ),
        migrations.AddField(
            model_name='proxy',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
