# Generated by Django 2.1.7 on 2019-04-10 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0050_auto_20190410_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('saved_cnt', models.IntegerField()),
                ('skiped_cnt', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Accounts')),
                ('source_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.SourceProfile')),
            ],
            options={
                'db_table': 'parsing_history',
            },
        ),
    ]
