# Generated by Django 2.1.7 on 2019-04-20 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0053_promohistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Proxy'),
        ),
    ]
