# Generated by Django 2.1.7 on 2019-04-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0054_auto_20190420_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsinghistory',
            name='ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parsinghistory',
            name='traceback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parsinghistory',
            name='saved_cnt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parsinghistory',
            name='skiped_cnt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
