# Generated by Django 2.1.7 on 2019-04-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0056_textcontent_ignore'),
    ]

    operations = [
        migrations.AddField(
            model_name='promohistory',
            name='process_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
