# Generated by Django 2.1.7 on 2019-05-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0061_textcontent_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='fb_email',
            field=models.EmailField(blank=True, max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='fb_pass',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
