# Generated by Django 2.1.7 on 2019-05-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0062_auto_20190511_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedchat',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
