# Generated by Django 2.1.7 on 2019-05-26 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0063_approvedchat_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalProxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uid', models.CharField(blank=True, max_length=1024, null=True)),
                ('country', models.CharField(max_length=1024)),
                ('host', models.CharField(max_length=1024)),
                ('port', models.PositiveIntegerField()),
                ('username', models.CharField(blank=True, max_length=1024, null=True)),
                ('password', models.CharField(blank=True, max_length=1024, null=True)),
                ('ip', models.GenericIPAddressField()),
                ('active', models.BooleanField()),
                ('ended', models.DateTimeField()),
                ('proxy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Proxy')),
            ],
            options={
                'db_table': 'external_proxy',
            },
        ),
    ]
