# Generated by Django 2.1.7 on 2019-06-07 08:48

import database.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0065_auto_20190602_0724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Looked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('story_id', models.CharField(blank=True, max_length=1024, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Accounts')),
            ],
            options={
                'db_table': 'looked',
            },
            bases=(models.Model, database.helpers.SaveAsyncMixin),
        ),
        migrations.AlterField(
            model_name='profile',
            name='promo_type',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)], db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='looked',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Profile'),
        ),
        migrations.AlterUniqueTogether(
            name='looked',
            unique_together={('profile', 'owner', 'story_id')},
        ),
    ]
