# Generated by Django 2.1.7 on 2019-07-01 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0066_auto_20190607_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ig_id', models.CharField(max_length=1024)),
                ('created', models.DateField(auto_now_add=True)),
                ('taken_at', models.BigIntegerField()),
                ('media_type', models.PositiveIntegerField()),
                ('code', models.CharField(max_length=1024)),
                ('comment_count', models.PositiveIntegerField()),
                ('like_count', models.PositiveIntegerField()),
                ('url', models.URLField()),
                ('approved', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Accounts')),
                ('posted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Posted')),
            ],
            options={
                'db_table': 'old_post',
            },
        ),
    ]
