# Generated by Django 2.1.7 on 2019-06-22 14:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0066_auto_20190607_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='looked',
            name='items_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), blank=True, null=True, size=None),
        ),
        migrations.AlterUniqueTogether(
            name='looked',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='looked',
            name='story_id',
        ),
    ]
