# Generated by Django 2.1.7 on 2019-07-01 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0067_oldpost'),
        ('database', '0067_auto_20190622_1441'),
    ]

    operations = [
    ]
