# Generated by Django 2.1.7 on 2019-07-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0068_merge_20190701_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldpost',
            name='url',
            field=models.URLField(max_length=4096),
        ),
    ]
