# Generated by Django 2.1.7 on 2019-07-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0069_auto_20190701_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldpost',
            name='image_name',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='oldpost',
            name='approved',
            field=models.NullBooleanField(default=None),
        ),
    ]
