# Generated by Django 2.1.7 on 2019-07-01 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0071_auto_20190701_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldpost',
            name='text_content',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.TextContent'),
        ),
    ]
