# Generated by Django 2.1.7 on 2019-07-06 09:08

import database.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0072_auto_20190701_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimonlineTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tzid', models.CharField(max_length=1024)),
                ('country_code', models.PositiveIntegerField()),
                ('phone', models.CharField(max_length=1024)),
                ('sms_code', models.CharField(blank=True, max_length=1024, null=True)),
                ('sms_code_timestamp', models.DateTimeField(blank=True, null=True)),
                ('confirmed_timestamp', models.DateTimeField(blank=True, null=True)),
                ('getting_attempts', models.PositiveIntegerField(default=0)),
                ('success', models.NullBooleanField(default=None)),
            ],
            options={
                'db_table': 'simonline_transaction',
            },
            bases=(models.Model, database.helpers.SaveAsyncMixin),
        ),
    ]
