# Generated by Django 2.1.7 on 2019-07-12 13:53

import database.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0074_simonlinetransaction_owner_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ig_id', models.BigIntegerField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('like_count', models.IntegerField()),
                ('user_ig_id', models.BigIntegerField()),
                ('user_username', models.CharField(max_length=1024)),
                ('user_full_name', models.CharField(max_length=1024)),
                ('user_is_private', models.BooleanField()),
                ('media_ig_id', models.CharField(max_length=1024)),
                ('media_code', models.CharField(max_length=1024)),
                ('media_taken_at', models.DateTimeField()),
                ('media_caption', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'media_comments',
            },
            bases=(models.Model, database.helpers.SaveAsyncMixin),
        ),
        migrations.CreateModel(
            name='MediaLiker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ig_id', models.BigIntegerField()),
                ('user_username', models.CharField(max_length=1024)),
                ('user_full_name', models.CharField(max_length=1024)),
                ('user_is_private', models.BooleanField()),
                ('user_profile_pic_url', models.URLField(max_length=4094)),
                ('media_ig_id', models.CharField(max_length=1024)),
                ('media_code', models.CharField(max_length=1024)),
                ('media_taken_at', models.DateTimeField()),
                ('media_caption', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'media_likers',
            },
            bases=(models.Model, database.helpers.SaveAsyncMixin),
        ),
    ]
