# Generated by Django 2.1.7 on 2019-07-12 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0075_mediacomments_medialiker'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediacomments',
            name='user_profile_pic_url',
            field=models.URLField(default=django.utils.timezone.now, max_length=4094),
            preserve_default=False,
        ),
    ]
